Repository wp-cli/media-command, pull requests merged in 2019-04, with the labels that each got.

#102 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
Labels: scope:distribution

#105 Enhancement: Add PHP 7.3 to Travis CI build matrix
  .travis.yml
Labels: scope:testing

#106 Implement CS checking based on the `WP_CLI_CS` ruleset
  .distignore
  .gitignore
  composer.json
  media-command.php
  phpcs.xml.dist
  src/Media_Command.php
Labels: scope:testing

#103 Refactored aspects of the image collection and determination of sizes
  features/media-image-size.feature
  src/Media_Command.php
Labels: command:media-image-size
