Repository wp-cli/media-command, pull requests merged in 2023-02, with the labels that each got.

#177 Remove tests around square image thumbnail regeneration
  features/media-regenerate.feature
Labels: command:media-regenerate, scope:testing

#176 Replace empty namespace autoloader with classmap
  composer.json
Labels: scope:distribution

#178 Add `composer phpcbf`
  composer.json
Labels: scope:testing
